"""empty message

Revision ID: f2e1eb74be85
Revises: 
Create Date: 2026-06-17 20:57:07.377751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e1eb74be85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_publish_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('instructor_id', sa.String(length=36), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_publish_facts_course_id'), 'course_publish_facts', ['course_id'], unique=True)
    op.create_index(op.f('ix_course_publish_facts_instructor_id'), 'course_publish_facts', ['instructor_id'], unique=False)
    op.create_table('enrollment_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_facts_course_id'), 'enrollment_facts', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollment_facts_enrollment_id'), 'enrollment_facts', ['enrollment_id'], unique=True)
    op.create_index(op.f('ix_enrollment_facts_student_id'), 'enrollment_facts', ['student_id'], unique=False)
    op.create_table('failed_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_events_event_type'), 'failed_events', ['event_type'], unique=False)
    op.create_table('progress_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('completed_modules', sa.Integer(), nullable=False),
    sa.Column('total_modules', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_facts_course_id'), 'progress_facts', ['course_id'], unique=False)
    op.create_index(op.f('ix_progress_facts_enrollment_id'), 'progress_facts', ['enrollment_id'], unique=True)
    op.create_index(op.f('ix_progress_facts_student_id'), 'progress_facts', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_facts_student_id'), table_name='progress_facts')
    op.drop_index(op.f('ix_progress_facts_enrollment_id'), table_name='progress_facts')
    op.drop_index(op.f('ix_progress_facts_course_id'), table_name='progress_facts')
    op.drop_table('progress_facts')
    op.drop_index(op.f('ix_failed_events_event_type'), table_name='failed_events')
    op.drop_table('failed_events')
    op.drop_index(op.f('ix_enrollment_facts_student_id'), table_name='enrollment_facts')
    op.drop_index(op.f('ix_enrollment_facts_enrollment_id'), table_name='enrollment_facts')
    op.drop_index(op.f('ix_enrollment_facts_course_id'), table_name='enrollment_facts')
    op.drop_table('enrollment_facts')
    op.drop_index(op.f('ix_course_publish_facts_instructor_id'), table_name='course_publish_facts')
    op.drop_index(op.f('ix_course_publish_facts_course_id'), table_name='course_publish_facts')
    op.drop_table('course_publish_facts')
    # ### end Alembic commands ###
